# Generated by Django 3.0.6 on 2020-05-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('guid', models.CharField(max_length=60)),
                ('headshot', models.CharField(max_length=80)),
                ('shortname', models.CharField(max_length=40)),
                ('fullname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('shortdesc', models.TextField()),
                ('fulldesc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('logo', models.CharField(max_length=10)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Division')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('string', models.CharField(max_length=10)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('main', models.CharField(max_length=10)),
                ('alt', models.CharField(max_length=10)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='OppStat',
            fields=[
                ('value', models.FloatField()),
                ('string', models.CharField(max_length=10)),
                ('teamstat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.TeamStat')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerNav',
            fields=[
                ('home', models.CharField(max_length=80)),
                ('headshot', models.CharField(max_length=80)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('abbr', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=60)),
                ('divrank', models.IntegerField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNav',
            fields=[
                ('home', models.CharField(max_length=80)),
                ('stats', models.CharField(max_length=80)),
                ('schedule', models.CharField(max_length=80)),
                ('roster', models.CharField(max_length=80)),
                ('depthchart', models.CharField(max_length=80)),
                ('injuries', models.CharField(max_length=80)),
                ('transactions', models.CharField(max_length=80)),
                ('blog', models.CharField(max_length=80)),
                ('logo', models.CharField(max_length=80)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('string', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
    ]
