# Generated by Django 3.0.6 on 2020-05-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200512_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sortkey',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='fullname',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
            preserve_default=False,
        ),
    ]
