# Generated by Django 3.0.6 on 2020-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200513_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
