# Generated by Django 3.0.6 on 2020-05-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200513_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
