# Generated by Django 3.0.6 on 2020-05-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200514_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shortname',
        ),
    ]
